-- =========================================================
-- PetNest Database Schema
-- Purpose: Complete 8-table MySQL database script.
-- Scope: Database / System
-- =========================================================
